version: '3'
services:
  app:
    build: ./backend
    restart: always
    depends_on:
      - db
    ports:
      - 9000:9000
  db:
    build: ./db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=devcamp_2023
    ports:
      - 9001:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: