name: Feishu Notification
on:
  pull_request:
    types: [opened]

jobs:
  pr-opened:
    name: Pull Request Opened Notification
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - uses: actions/github-script@v4
        id: set-template-values
        with:
          script: |
            return JSON.stringify({
              pr_title: "${{ github.event.pull_request.title }}",
              pr_user: "${{ github.event.pull_request.user.login }}",
              pr_user_url: "https://github.com/${{ github.event.pull_request.user.login }}",
              pr_url: "https://github.com/${{ github.repository }}/pull/${{ github.event.pull_request.number }}",
            })
          result-encoding: string

      - name: Send feishu message
        env:
          ACTIONS_FEISHU_TAG: "v1.3.1"
          INPUT_WEBHOOK: "${{ secrets.FEISHU_ROBOT_WEBHOOK_URL }}"
          INPUT_MESSAGE_TYPE: template
          INPUT_MSG_TEMPLATE_PATH: ".github/workflows/feishu-template/template.json"
          INPUT_MSG_TEMPLATE_VALUES: "${{ steps.set-template-values.outputs.result }}"
        run: |
          curl -L -O https://github.com/xiachufang/actions-feishu/releases/download/${{ env.ACTIONS_FEISHU_TAG }}/darwin-amd64-actions-feishu.tar.gz
          tar zxf darwin-amd64-actions-feishu.tar.gz feishu
          ./feishu
