name: Feishu Notification

on:
  pull_request:
    types: [opened]

jobs:
  pr-opened:
    name: Pull Request Opened Notification
    if: ${{ github.event_name == 'pull_request' && github.event.action == 'opened' }}
    runs-on: self-hosted
    steps:
      - name: Send Feishu Message
        env:
          ACTIONS_FEISHU_TAG: v1.3.1
          INPUT_WEBHOOK: ${{ secrets.FEISHU_ROBOT_WEBHOOK_URL }}
          INPUT_MESSAGE_TYPE: post
          INPUT_TITLE: New Pull Request
          INPUT_CONTENT: |
            @${{ github.event.pull_request.user.login }} opened pull request #${{ github.event.pull_request.number }}:

                ${{ github.event.pull_request.title }}
            
            See: https://github.com/${{ github.repository }}/pull/${{ github.event.pull_request.number }}

        run: |
          curl https://github.com/xiachufang/actions-feishu/releases/download/${{ env.ACTIONS_FEISHU_TAG }}/darwin-amd64-actions-feishu.tar.gz
          tar zxf darwin-amd64-actions-feishu.tar.gz feishu
          ./feishu
